### ISSUE TITLE
Dropdown frame goes behind last colors

### ISSUE THREAD

**Issue by shadofall** [muhmiauwau/ColorTools#1]
the Dropdown frame to choos elast used/class etc goes down behind the last used colors list so the options cant be changed

![image](https://github.com/user-attachments/assets/c9d332ba-10e0-449f-9aff-01c4d3fcdde4)

**Comment by muhmiauwau** [comment]
Hello, thanks for the hint. It could be a problem with the new blizzard dropdown. I take that version down. the last version (1.0.0) should work fine.

**Comment by muhmiauwau** [comment]
Ok, that was a wired bug with AceGUI. It should be fixed with Version 1.1.1.
