### ISSUE TITLE
Context menu (add favorite) inaccessible due to frame strata/level too low

### ISSUE THREAD

**Issue by tflo** [muhmiauwau/ColorTools#3]
I’m having a similar problem like in #1, but with the Favorite context menu: cannot add a favorite because the menu is behind the main frame.

There’s also a [post on your CF Issues page](https://legacy.curseforge.com/wow/addons/colortools-color-picker/issues/2) which describes apparently the same problem.

**Comment by muhmiauwau** [comment]
Hi,
thank you for reporting this issue. It is fixed with release 1.7.1.

Sorry for the delay, i missed the issue on CF.

**Comment by tflo** [comment]
> i missed the issue on CF.

You can make your “Issues“ link on CurseForge point directly to your GitHub Issues. Go to your project settings > Issues > choose “External” and paste the link to this Issues page.
